---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-operator
rules:
- apiGroups:
  - drzhangg.my.domain
  resources:
  - frigates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - drzhangg.my.domain
  resources:
  - frigates/finalizers
  verbs:
  - update
- apiGroups:
  - drzhangg.my.domain
  resources:
  - frigates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - ""
  resources:
    - "*"
  verbs:
    - "*"
